#' ck_create_pert_params
#'
#' creates an \code{\link{pert_params-class}} object containing information
#' about perturbation parameters
#' @param big_n (integer) large prime number used to derive cell keys from
#' record keys
#' @param small_n (integer) parameter that controlls how the columns of
#' \code{pTable} are scrolled
#' @param ptab a perturbation table generated with
#' \code{\link{ck_create_ptab}} or \code{\link{ck_create_free_ptable}}
#' @param stab table containing the noise component for numerical variables
#' generated by \code{\link{ck_generate_stab}}
#' @param mtab (numeric) vector containing parameters for the magnitude of
#' perturbation for numerical variables
#'
#' @return an object of \code{\link{pert_params-class}}
#' @export
#' @seealso \url{https://preview.tinyurl.com/yyleyg48}
#' @examples
#' pTable <- ck_create_ptab(
#'   type = "destatis",
#'   D = 5,
#'   V = 3
#' )
#' params <- ck_create_pert_params(
#'   big_n = 17312941,
#'   small_n = 12,
#'   ptab = pTable,
#'   stab = ck_generate_stab(small_c = 12),
#'   mtab = c(0.6, 0.4, 0.2))
#' print(class(params))
ck_create_pert_params <-
  function(big_n = NULL,
           small_n = NULL,
           ptab,
           stab = NULL,
           mtab = NULL) {

  .convert <- function(ptab) {
      . <- i <- p_int_ub <- v <- NULL
      if (isS4(ptab) && class(ptab) == "ptable") {
        pType <- slot(ptab, "type")
        if (pType == "destatis") {
          ptab <- slot(ptab, "pTable")[, .(i, p_int_ub, v)]
          setnames(ptab, c("i", "kum_p_o", "diff"))
        }
        if (pType %in% c("abs", "free")) {
          ptab <- slot(ptab, "pTable")
        }
      }
      ptab
    }

  out <- new("pert_params")
  slot(out, "type") <- slot(ptab, "type")
  ptab <- .convert(ptab)

  cur_type <- slot(out, "type")
  if (cur_type == "destatis") {
    m <- c(
      "The supplied pTable is of type `destatis`.",
      "Arguments `small_n` and `big_n` are therefore ignored."
    )
    mf <- match.call(expand.dots = FALSE)
    if (!is.null(mf$big_n) | !is.null(small_n)) {
      message(paste(m, collapse = " "))
    }
    message(paste(m, collapse = " "))
    slot(out, "big_n") <- as.integer(1)
    slot(out, "small_n") <- 0L
  } else if (cur_type %in% c("abs", "free")) {
    stopifnot(is.numeric(big_n), length(big_n) == 1, big_n >= 1)
    if (big_n > .Machine$integer.max) {
      e <- c(
        "The number provided for `big_n` is larger than the",
        "maximum possible value on your computer",
        paste0("(", .Machine$integer.max, ")")
      )
      stop(paste(e, collapse = " "), call. = FALSE)
    }
    stopifnot(is_bare_integerish(big_n))
    stopifnot(is_bare_integerish(small_n), small_n >= 1)
    slot(out, "big_n") <- as.integer(big_n)
    slot(out, "small_n") <- as.integer(small_n)
  } else {
    stop("invalid input!\n")
  }
  slot(out, "ptab") <- ptab
  slot(out, "ptab_size") <- as.integer(ncol(ptab))

  if (slot(out, "small_n") >= slot(out, "ptab_size")) {
    e <- c(
      "Parameter `small_n` must be smaller than the number",
      "of columns in `ptab`"
    )
    stop(paste(e, collapse = " "), call. = FALSE)
  }

  if (!is.null(mtab)) {
    slot(out, "mtab") <- mtab
    slot(out, "top_k") <- as.integer(length(mtab))
  }
  if (!is.null(stab)) {
    slot(out, "stab") <- stab
    slot(out, "small_c") <- as.integer(ncol(stab) - 32)
  }
  validObject(out)
  out
}
