#' ck_create_pert_params
#'
#' creates an \code{\link{pert_params-class}} object containing information
#' about perturbation parameters
#' @param bigN (integer) large prime number used to derive cell keys from record keys
#' @param smallN (integer) parameter that controlls how the columns of \code{pTable} are scrolled
#' @param pTable a perturbation table generated with \code{\link{ck_create_pTable}}
#' @param sTable table containing the noise component for numerical variables generated by
#' \code{\link{ck_generate_sTable}}
#' @param mTable (numeric) vector containing parameters for the magnitude of perturbation for numerical variables
#'
#' @return an object of \code{\link{pert_params-class}}
#' @export
#' @seealso \url{https://www.unece.org/fileadmin/DAM/stats/documents/ece/ces/ge.46/2013/Topic_1_ABS.pdf}
#' @examples
#' params <- ck_create_pert_params(
#'   bigN=17312941,
#'   smallN=12,
#'   pTable=ck_create_pTable(pTableSize=70),
#'   sTable=ck_generate_sTable(smallC=12),
#'   mTable=c(0.6,0.4,0.2))
#' print(class(params))
ck_create_pert_params <- function(bigN, smallN, pTable, sTable, mTable) {
  out <- new("pert_params")

  slot(out, "type") <- attr(pTable, "type")

  if (slot(out, "type")=="destatis") {
    message("Note: the supplied pTable is of type 'destatis'. Thus, arguments 'bigN' and 'smallN' will be ignored:")
    slot(out, "bigN") <- as.integer(3)
    slot(out, "smallN") <- 0L
  } else {
    stopifnot(is_bare_integerish(bigN))
    stopifnot(is_bare_integerish(smallN))
    slot(out, "bigN") <- as.integer(bigN)
    slot(out, "smallN") <- as.integer(smallN)
  }
  slot(out, "pTable") <- pTable
  slot(out, "pTableSize") <- as.integer(ncol(pTable))
  slot(out, "mTable") <- mTable
  slot(out, "sTable") <- sTable
  slot(out, "smallC") <- as.integer(ncol(sTable)-32)
  slot(out, "topK") <- as.integer(length(mTable))

  validObject(out)
  out
}
